//
// Created by taoy3 on 16/9/5.
//
#include <jni.h>
#ifndef SMARTHOMEDEMO_COM_TAOY3_NDKDEMO_NATIVETEST_H
#define SMARTHOMEDEMO_COM_TAOY3_NDKDEMO_NATIVETEST_H

#endif //SMARTHOMEDEMO_COM_TAOY3_NDKDEMO_NATIVETEST_H
